Controllers/AgentiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Municipale.Models;

namespace Municipale.Controllers
{
    public class AgentiController : Controller
    {
        private readonly MunicipaleContext _context;

        public AgentiController(MunicipaleContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Agente> agenti = await _context.Agenti.ToListAsync();
            return View(agenti);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Agente agente)
        {
            if (ModelState.IsValid)
            {
                _context.Agenti.Add(agente);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/AnagraficaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Municipale.Models;

namespace Municipale.Controllers
{
    public class AnagraficaController : Controller
    {
        private readonly MunicipaleContext _context;
        
        public AnagraficaController(MunicipaleContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Anagrafica> anagrafica = await _context.Anagrafica.ToListAsync();
            return View(anagrafica);
        }
    }
}

Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Municipale.Models;


namespace Municipale.Controllers
{
    public class ReportController : Controller
    {
        private readonly MunicipaleContext _context;

        public ReportController(MunicipaleContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var reportTotali = await Report();
            var violazioni400 = await GetMaggiori400Euro();
            var punti10 = await GetPunti10();

            var model = new List<List<Report>>
    {
        reportTotali,
        violazioni400,
        punti10
    };
            return View(model);
        }

        public async Task<IActionResult> Violazioni()
        {
            var violazioni400 = await GetMaggiori400Euro();
            return View(violazioni400);
        }

        public async Task<IActionResult> Punti()
        {
            var punti10 = await GetPunti10();
            return View(punti10);
        }

        private async Task<List<Report>> Report()
        {
            var reports = new List<Report>();

            var verbaliPerTrasgressore = await _context.Verbali
                .GroupBy(v => new { v.IDAnagrafe })
                .Select(g => new
                {
                    IDAnagrafe = g.Key.IDAnagrafe,
                    TotaleVerbali = g.Count(),
                    TotalePuntiDecurtati = g.Sum(v => v.DecurtamentoPunti)
                })
                .ToListAsync();

            foreach (var item in verbaliPerTrasgressore)
            {
                var anagrafica = await _context.Anagrafica.FindAsync(item.IDAnagrafe);
                var trasgressore = anagrafica != null ? $"{anagrafica.Cognome} {anagrafica.Nome}" : "Anagrafica non trovata";

                var report = new Report
                {
                    Trasgressore = trasgressore,
                    TotaleVerbali = item.TotaleVerbali,
                    TotalePuntiDecurtati = item.TotalePuntiDecurtati
                    
                };
                reports.Add(report);
            }
            return reports;
        }

        private async Task<List<Report>> GetMaggiori400Euro()
        {
            var reports = new List<Report>();

            var verbaliPerTrasgressore = await _context.Verbali
                .Where(v => v.Importo > 400)
                .ToListAsync();

            foreach (var verbale in verbaliPerTrasgressore)
            {
                var trasgressoreName = await GetTrasgressoreName(verbale.IDAnagrafe);

                var report = new Report
                {
                    Trasgressore = trasgressoreName,
                    DataViolazione = verbale.DataViolazione,
                    IndirizzoViolazione = verbale.IndirizzoViolazione,
                    Importo = verbale.Importo,
                    TotalePuntiDecurtati = verbale.DecurtamentoPunti
                };
                reports.Add(report);
            }

            return reports;
        }

        private async Task<List<Report>> GetPunti10()
        {
            var reports = new List<Report>();

            var verbaliPerTrasgressore = await _context.Verbali
                .Where(v => v.DecurtamentoPunti > 10)
                .ToListAsync();

            foreach (var verbale in verbaliPerTrasgressore)
            {
                var trasgressoreName = await GetTrasgressoreName(verbale.IDAnagrafe);

                var report = new Report
                {
                    Trasgressore = trasgressoreName,
                    DataViolazione = verbale.DataViolazione,
                    IndirizzoViolazione = verbale.IndirizzoViolazione,
                    Importo = verbale.Importo,
                    TotalePuntiDecurtati = verbale.DecurtamentoPunti
                };
                reports.Add(report);
            }

            return reports;
        }


        private async Task<string> GetTrasgressoreName(int IDAnagrafe)
        {
            var anagrafica = await _context.Anagrafica.FindAsync(IDAnagrafe);
            return anagrafica != null ? $"{anagrafica.Cognome} {anagrafica.Nome}" : "Anagrafica non trovata";
        }
    }
}

Controllers/VerbaliController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Municipale.Models;

namespace Municipale.Controllers
{
    public class VerbaliController : Controller
    {
        private readonly MunicipaleContext _context;
        public VerbaliController(MunicipaleContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Verbale> Verbale = await _context.Verbali.ToListAsync();
            return View(Verbale);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Una bella multina</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/s7_l5.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js" defer></script>

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img class="img-fluid loghetto" src="/media/event.png" alt="logo" style="width: 10%;">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="margin-left: 15em;">Multina?!?!?</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Panello Controllo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Report</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anagrafica" asp-action="Index">Trasgressori</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Verbali" asp-action="Index">Verbali</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-black" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Agenti
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Agenti" asp-action="Index" >Lista Agenti</a></li>
                                <li><a class="dropdown-item" asp-controller="Agenti" asp-action="Add" >Aggiungi agente</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-black" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Violazioni
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="TipoViolazione" asp-action="Index" >Lista Violazioni</a></li>
                                <li><a class="dropdown-item" asp-controller="TipoViolazione" asp-action="Add" >Aggiungi violazione</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <img class="img-fluid loghetto" src="/media/aldo.jpeg" alt="logo" style="width: 15%;">
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>