Models/TipoViolazione.cs
namespace Municipale.Models
{
    public class TipoViolazione
    {
        public int ID { get; set; }
        public string? Descrizione { get; set; }
    }
}

Controllers/TipoViolazioneController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Municipale.Models;

namespace Municipale.Controllers
{
    public class TipoViolazioneController : Controller
    {
        private readonly MunicipaleContext _context;

        public TipoViolazioneController(MunicipaleContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<TipoViolazione> TipoViolazione = await _context.TipoViolazione.ToListAsync();
            return View(TipoViolazione);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public  IActionResult Add(TipoViolazione tipoViolazione)
        {
            if (ModelState.IsValid)
            {
                _context.TipoViolazione.Add(tipoViolazione);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var violazione = await _context.TipoViolazione.FindAsync(id);
            if (violazione == null)
            {
                return NotFound();
            }

            return View(violazione);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfermata(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var violazione = await _context.TipoViolazione.FindAsync(id);
            if (violazione == null)
            {
                return NotFound();
            }

            _context.TipoViolazione.Remove(violazione);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/TipoViolazione/Add.cshtml
@model TipoViolazione

<h1>Aggiungi violazione</h1>

<form asp-controller="TipoViolazione" asp-action="Add" method="post">
            <div class="form-group">
                <label asp-for="Descrizione" class="control-label">Descrione</label>
                <input asp-for="Descrizione" class="form-control" />
            </div>
            <button type="submit" class="btn btn-primary">Aggiungi</button>
</form>

Views/TipoViolazione/Delete.cshtml
@model TipoViolazione

@{
    ViewData["Title"] = "Conferma Eliminazione";
}

<div class="container">
    <h4>Conferma eliminazione di  @Model.Descrizione</h4>
    <span class="bg-danger text-white">Questa azione non è reversibile</span>

    <form asp-controller="TipoViolazione" asp-action="DeleteConfermata" method="post">
        <input type="hidden" name="id" value="@Model.ID" />
        <button type="submit" class="btn btn-danger">Elimina</button>
    </form>

</div>

Views/TipoViolazione/Index.cshtml
@{
    ViewData["Title"] = "Elenco violazioni";
}

<div class="container">
    <h1>Elenco violazioni</h1>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Descrizione</th>
                <th>Azioni</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var violazione in Model)
            {
                <tr>
                    <td>@violazione.ID</td>
                    <td>@violazione.Descrizione</td>
                    <td><a class="btn btn-danger" asp-controller="TipoViolazione" asp-action="Delete" asp-route-id="@violazione.ID">Elimina</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>